config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :comments
  resources :posts do
    member do
      post 'add_like'
      post 'add_dislike'
    end
    resources :comments, only: [:create]

  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "welcome#index"

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  include PgSearch::Model
  pg_search_scope :search_full_text, against: {
    title: 'A',
    message: 'B'
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

#usuario ejecutivo
before_action only: [:new, :edit, :create, :update] do
  authorize_request(["super"])
end
#usuario admin
before_action only: [:destroy] do
  authorize_request(["super"])
end

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @consulta = params[:buscar]
    if @consulta.present?
      @posts = Post.search_full_text(@consulta)
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = @post.comments.build

    if current_user.present?
    @current_user_id = current_user.id
    end
    @comments = Comment.where(post_id: @post.id).order(created_at: :desc)

    #contar likes y dislikes
    connection = ActiveRecord::Base.connection

    result_likes = connection.execute("SELECT COUNT(*) FROM posts_users WHERE reaccion = 'L' AND post_id = #{@post.id}")
    @likes = result_likes.first['count'].to_i

    result_dislikes = connection.execute("SELECT COUNT(*) FROM posts_users WHERE reaccion = 'D' AND post_id = #{@post.id}")
    @dislikes = result_dislikes.first['count'].to_i

  end

  # GET /posts/new
  def new
    @post = Post.new


  end

  def add_like
    post = Post.find(params[:id])
    user_id = current_user.id

    # Verificamos si el usuario ya ha dado like o dislike al post
    existing_post_user = ActiveRecord::Base.connection.execute("SELECT * FROM posts_users WHERE post_id = #{post.id} AND user_id = #{user_id}").first

    # Si el usuario aún no ha dado like o dislike, agregamos un nuevo reaccion
    if existing_post_user.nil?
      ActiveRecord::Base.connection.execute("
        INSERT INTO posts_users (post_id, user_id, reaccion)
        VALUES (#{post.id}, #{user_id}, 'L')
      ")
      flash[:notice] = "Like agregado correctamente."
    else
      flash[:notice] = "Ya has dado like o dislike a este post."
    end

    redirect_to post_path(post)
  end

def add_dislike
  post = Post.find(params[:id])
  user_id = current_user.id

  # Verificamos si el usuario ya ha dado like o dislike al post
  existing_post_user = ActiveRecord::Base.connection.execute("SELECT * FROM posts_users WHERE post_id = #{post.id} AND user_id = #{user_id}").first

  # Si el usuario aún no ha dado like o dislike, agregamos un nuevo reaccion
  if existing_post_user.nil?
    ActiveRecord::Base.connection.execute("
      INSERT INTO posts_users (post_id, user_id, reaccion)
      VALUES (#{post.id}, #{user_id}, 'D')
    ")
    flash[:notice] = "Like agregado correctamente."
  else
    flash[:notice] = "Ya has dado like o dislike a este post."
  end

  redirect_to post_path(post)
end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :message)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message, class:"form-control" %>
  </div>

  <div class="mt-5">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="card mt-3 mb-1">
    <div class="card-body">
      <h1 class="card-title"><%= post.title %></h1>
      <p class="card-text"><%= truncate(post.message, length: 300) %></p>
      <span><%= post.user.name %></span>
      <p>
        <% if user_signed_in? %>
          <% if params[:id].present?%>
            <hr>
            <div class="row text-center">
              <div class="col-6">
              <span class="text-info">LIKES: <%= @likes %></span>

                <%= button_to 'Like', add_like_post_path(@post), method: :post, class: 'btn btn-info' %>
              </div>
              <div class="col-6">
              <span class="text-danger">DISLIKES: <%= @dislikes %></span>

                <%= button_to 'Dislike', add_dislike_post_path(@post), method: :post, class: 'btn btn-danger' %>
              </div>
            </div>
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Mostrar este Post", @post, class: "btn btn-primary"  %> |
  <%= link_to "Volver a Post", posts_path, class: "btn btn-secondary" %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>
<% if user_signed_in? %>
  <%= link_to "Nueva Publicación", new_post_path, class: "btn btn-success my-4" %>
<% end %>
<div id="posts" class="col-12">
  <div id="posts" class="row">
    <% @posts.each do |post| %>
      <div class="col-6">
        <%= render post %>
        <p>
          <%= link_to "Ver esta publicación", post, class: "btn btn-sm btn-primary" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Volver a posts", posts_path, class:"btn btn-secondary" %>
</div>

app/views/posts/show.html.erb
<%= render @post %>
<div>
  <div class="btn-group mt-1" role="group" aria-label="Basic example">
    <% if user_signed_in? %>
      <%= link_to "Editar este post", edit_post_path(@post), class:"btn btn-warning" %>
    <% end %>
    <%= link_to "Volver a posts", posts_path, class:"btn btn-secondary" %>
  </div>
  <div class="row my-4">
    <hr class="text-success">
    <h4 class="text-success">Comentar</h4>
    <%= form_for([@post, @comment]) do |form| %>
      <!-- Otros campos del formulario -->
      <%= form.text_area :message, class: "form-control" %>
      <br>
      <%= form.submit "Enviar", class: "btn btn-success" %>
    <% end %>
  </div>
  <div class="row">
    <h4>Comentarios</h4>
    <% @comments.each do |comment| %>
      <p>
        <%= comment.message %>
        <br>
        <% if comment.logueado == true  %>
          <small>comment by: <%= comment.user.name %> - <%= comment.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></small>
        <% else %>
          <small>comment by: Desconocido - <%= comment.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></small>
        <% end %>
      </p>
      <hr>
      <!-- Otros atributos del comentario que deseas mostrar -->
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="row my-4">
      <hr class="text-danger">
      <h4 class="text-danger">Eliminar</h4>
      <%= button_to "Eliminar este post", @post, method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>